// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SceneViewer.proto

#include "SceneViewer.pb.h"
#include "SceneViewer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* SceneStreamerService_method_names[] = {
  "/SceneStreamerService/SendSceneRequest",
  "/SceneStreamerService/RequestSceneFilePaths",
};

std::unique_ptr< SceneStreamerService::Stub> SceneStreamerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SceneStreamerService::Stub> stub(new SceneStreamerService::Stub(channel, options));
  return stub;
}

SceneStreamerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendSceneRequest_(SceneStreamerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_RequestSceneFilePaths_(SceneStreamerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::FileChunkReply>* SceneStreamerService::Stub::SendSceneRequestRaw(::grpc::ClientContext* context, const ::SceneRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::FileChunkReply>::Create(channel_.get(), rpcmethod_SendSceneRequest_, context, request);
}

void SceneStreamerService::Stub::async::SendSceneRequest(::grpc::ClientContext* context, const ::SceneRequest* request, ::grpc::ClientReadReactor< ::FileChunkReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::FileChunkReply>::Create(stub_->channel_.get(), stub_->rpcmethod_SendSceneRequest_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::FileChunkReply>* SceneStreamerService::Stub::AsyncSendSceneRequestRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileChunkReply>::Create(channel_.get(), cq, rpcmethod_SendSceneRequest_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::FileChunkReply>* SceneStreamerService::Stub::PrepareAsyncSendSceneRequestRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileChunkReply>::Create(channel_.get(), cq, rpcmethod_SendSceneRequest_, context, request, false, nullptr);
}

::grpc::Status SceneStreamerService::Stub::RequestSceneFilePaths(::grpc::ClientContext* context, const ::EmptyMsg& request, ::SceneFilepathsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::EmptyMsg, ::SceneFilepathsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestSceneFilePaths_, context, request, response);
}

void SceneStreamerService::Stub::async::RequestSceneFilePaths(::grpc::ClientContext* context, const ::EmptyMsg* request, ::SceneFilepathsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::EmptyMsg, ::SceneFilepathsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestSceneFilePaths_, context, request, response, std::move(f));
}

void SceneStreamerService::Stub::async::RequestSceneFilePaths(::grpc::ClientContext* context, const ::EmptyMsg* request, ::SceneFilepathsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestSceneFilePaths_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SceneFilepathsReply>* SceneStreamerService::Stub::PrepareAsyncRequestSceneFilePathsRaw(::grpc::ClientContext* context, const ::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SceneFilepathsReply, ::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestSceneFilePaths_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SceneFilepathsReply>* SceneStreamerService::Stub::AsyncRequestSceneFilePathsRaw(::grpc::ClientContext* context, const ::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestSceneFilePathsRaw(context, request, cq);
  result->StartCall();
  return result;
}

SceneStreamerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SceneStreamerService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SceneStreamerService::Service, ::SceneRequest, ::FileChunkReply>(
          [](SceneStreamerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SceneRequest* req,
             ::grpc::ServerWriter<::FileChunkReply>* writer) {
               return service->SendSceneRequest(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SceneStreamerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SceneStreamerService::Service, ::EmptyMsg, ::SceneFilepathsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SceneStreamerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::EmptyMsg* req,
             ::SceneFilepathsReply* resp) {
               return service->RequestSceneFilePaths(ctx, req, resp);
             }, this)));
}

SceneStreamerService::Service::~Service() {
}

::grpc::Status SceneStreamerService::Service::SendSceneRequest(::grpc::ServerContext* context, const ::SceneRequest* request, ::grpc::ServerWriter< ::FileChunkReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SceneStreamerService::Service::RequestSceneFilePaths(::grpc::ServerContext* context, const ::EmptyMsg* request, ::SceneFilepathsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


