// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SceneViewer.proto
// Protobuf C++ Version: 5.29.3

#include "SceneViewer.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr SceneRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : scenename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SceneRequest::SceneRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SceneRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SceneRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SceneRequestDefaultTypeInternal() {}
  union {
    SceneRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SceneRequestDefaultTypeInternal _SceneRequest_default_instance_;

inline constexpr SceneFilepathsReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : paths_{},
        filenames_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SceneFilepathsReply::SceneFilepathsReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SceneFilepathsReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SceneFilepathsReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SceneFilepathsReplyDefaultTypeInternal() {}
  union {
    SceneFilepathsReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SceneFilepathsReplyDefaultTypeInternal _SceneFilepathsReply_default_instance_;

inline constexpr FileChunkReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : objfilename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        chunk1024_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        chunkorder_{0},
        chunktotal_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileChunkReply::FileChunkReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileChunkReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileChunkReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileChunkReplyDefaultTypeInternal() {}
  union {
    FileChunkReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileChunkReplyDefaultTypeInternal _FileChunkReply_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR EmptyMsg::EmptyMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EmptyMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyMsgDefaultTypeInternal() {}
  union {
    EmptyMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyMsgDefaultTypeInternal _EmptyMsg_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_SceneViewer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SceneViewer_2eproto = nullptr;
const ::uint32_t
    TableStruct_SceneViewer_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::SceneRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SceneRequest, _impl_.scenename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::FileChunkReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::FileChunkReply, _impl_.objfilename_),
        PROTOBUF_FIELD_OFFSET(::FileChunkReply, _impl_.chunk1024_),
        PROTOBUF_FIELD_OFFSET(::FileChunkReply, _impl_.chunkorder_),
        PROTOBUF_FIELD_OFFSET(::FileChunkReply, _impl_.chunktotal_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::EmptyMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::SceneFilepathsReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SceneFilepathsReply, _impl_.paths_),
        PROTOBUF_FIELD_OFFSET(::SceneFilepathsReply, _impl_.filenames_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::SceneRequest)},
        {9, -1, -1, sizeof(::FileChunkReply)},
        {21, -1, -1, sizeof(::EmptyMsg)},
        {29, -1, -1, sizeof(::SceneFilepathsReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_SceneRequest_default_instance_._instance,
    &::_FileChunkReply_default_instance_._instance,
    &::_EmptyMsg_default_instance_._instance,
    &::_SceneFilepathsReply_default_instance_._instance,
};
const char descriptor_table_protodef_SceneViewer_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021SceneViewer.proto\"!\n\014SceneRequest\022\021\n\ts"
    "ceneName\030\001 \001(\t\"`\n\016FileChunkReply\022\023\n\013objF"
    "ilename\030\001 \001(\t\022\021\n\tchunk1024\030\002 \001(\014\022\022\n\nchun"
    "kOrder\030\003 \001(\005\022\022\n\nchunkTotal\030\004 \001(\005\"\n\n\010Empt"
    "yMsg\"7\n\023SceneFilepathsReply\022\r\n\005paths\030\001 \003"
    "(\t\022\021\n\tfilenames\030\002 \003(\t2\206\001\n\024SceneStreamerS"
    "ervice\0224\n\020SendSceneRequest\022\r.SceneReques"
    "t\032\017.FileChunkReply0\001\0228\n\025RequestSceneFile"
    "Paths\022\t.EmptyMsg\032\024.SceneFilepathsReplyb\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_SceneViewer_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_SceneViewer_2eproto = {
    false,
    false,
    366,
    descriptor_table_protodef_SceneViewer_2eproto,
    "SceneViewer.proto",
    &descriptor_table_SceneViewer_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_SceneViewer_2eproto::offsets,
    file_level_enum_descriptors_SceneViewer_2eproto,
    file_level_service_descriptors_SceneViewer_2eproto,
};
// ===================================================================

class SceneRequest::_Internal {
 public:
};

SceneRequest::SceneRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SceneRequest)
}
inline PROTOBUF_NDEBUG_INLINE SceneRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::SceneRequest& from_msg)
      : scenename_(arena, from.scenename_),
        _cached_size_{0} {}

SceneRequest::SceneRequest(
    ::google::protobuf::Arena* arena,
    const SceneRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SceneRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:SceneRequest)
}
inline PROTOBUF_NDEBUG_INLINE SceneRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : scenename_(arena),
        _cached_size_{0} {}

inline void SceneRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SceneRequest::~SceneRequest() {
  // @@protoc_insertion_point(destructor:SceneRequest)
  SharedDtor(*this);
}
inline void SceneRequest::SharedDtor(MessageLite& self) {
  SceneRequest& this_ = static_cast<SceneRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.scenename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SceneRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SceneRequest(arena);
}
constexpr auto SceneRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SceneRequest),
                                            alignof(SceneRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SceneRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SceneRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SceneRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SceneRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SceneRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SceneRequest>(), &SceneRequest::ByteSizeLong,
            &SceneRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SceneRequest, _impl_._cached_size_),
        false,
    },
    &SceneRequest::kDescriptorMethods,
    &descriptor_table_SceneViewer_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SceneRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2> SceneRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SceneRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string sceneName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SceneRequest, _impl_.scenename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sceneName = 1;
    {PROTOBUF_FIELD_OFFSET(SceneRequest, _impl_.scenename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\11\0\0\0\0\0\0"
    "SceneRequest"
    "sceneName"
  }},
};

PROTOBUF_NOINLINE void SceneRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:SceneRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scenename_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SceneRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SceneRequest& this_ = static_cast<const SceneRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SceneRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SceneRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:SceneRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string sceneName = 1;
          if (!this_._internal_scenename().empty()) {
            const std::string& _s = this_._internal_scenename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "SceneRequest.sceneName");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:SceneRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SceneRequest::ByteSizeLong(const MessageLite& base) {
          const SceneRequest& this_ = static_cast<const SceneRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SceneRequest::ByteSizeLong() const {
          const SceneRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:SceneRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string sceneName = 1;
            if (!this_._internal_scenename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_scenename());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SceneRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SceneRequest*>(&to_msg);
  auto& from = static_cast<const SceneRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SceneRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_scenename().empty()) {
    _this->_internal_set_scenename(from._internal_scenename());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SceneRequest::CopyFrom(const SceneRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SceneRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SceneRequest::InternalSwap(SceneRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.scenename_, &other->_impl_.scenename_, arena);
}

::google::protobuf::Metadata SceneRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileChunkReply::_Internal {
 public:
};

FileChunkReply::FileChunkReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FileChunkReply)
}
inline PROTOBUF_NDEBUG_INLINE FileChunkReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FileChunkReply& from_msg)
      : objfilename_(arena, from.objfilename_),
        chunk1024_(arena, from.chunk1024_),
        _cached_size_{0} {}

FileChunkReply::FileChunkReply(
    ::google::protobuf::Arena* arena,
    const FileChunkReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileChunkReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chunkorder_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, chunkorder_),
           offsetof(Impl_, chunktotal_) -
               offsetof(Impl_, chunkorder_) +
               sizeof(Impl_::chunktotal_));

  // @@protoc_insertion_point(copy_constructor:FileChunkReply)
}
inline PROTOBUF_NDEBUG_INLINE FileChunkReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : objfilename_(arena),
        chunk1024_(arena),
        _cached_size_{0} {}

inline void FileChunkReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chunkorder_),
           0,
           offsetof(Impl_, chunktotal_) -
               offsetof(Impl_, chunkorder_) +
               sizeof(Impl_::chunktotal_));
}
FileChunkReply::~FileChunkReply() {
  // @@protoc_insertion_point(destructor:FileChunkReply)
  SharedDtor(*this);
}
inline void FileChunkReply::SharedDtor(MessageLite& self) {
  FileChunkReply& this_ = static_cast<FileChunkReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.objfilename_.Destroy();
  this_._impl_.chunk1024_.Destroy();
  this_._impl_.~Impl_();
}

inline void* FileChunkReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileChunkReply(arena);
}
constexpr auto FileChunkReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileChunkReply),
                                            alignof(FileChunkReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileChunkReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileChunkReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileChunkReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileChunkReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileChunkReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileChunkReply>(), &FileChunkReply::ByteSizeLong,
            &FileChunkReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_._cached_size_),
        false,
    },
    &FileChunkReply::kDescriptorMethods,
    &descriptor_table_SceneViewer_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileChunkReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 34, 2> FileChunkReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FileChunkReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 chunkTotal = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileChunkReply, _impl_.chunktotal_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunktotal_)}},
    // string objFilename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.objfilename_)}},
    // bytes chunk1024 = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunk1024_)}},
    // int32 chunkOrder = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileChunkReply, _impl_.chunkorder_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunkorder_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string objFilename = 1;
    {PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.objfilename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes chunk1024 = 2;
    {PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunk1024_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 chunkOrder = 3;
    {PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunkorder_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 chunkTotal = 4;
    {PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunktotal_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\16\13\0\0\0\0\0\0"
    "FileChunkReply"
    "objFilename"
  }},
};

PROTOBUF_NOINLINE void FileChunkReply::Clear() {
// @@protoc_insertion_point(message_clear_start:FileChunkReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.objfilename_.ClearToEmpty();
  _impl_.chunk1024_.ClearToEmpty();
  ::memset(&_impl_.chunkorder_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.chunktotal_) -
      reinterpret_cast<char*>(&_impl_.chunkorder_)) + sizeof(_impl_.chunktotal_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileChunkReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileChunkReply& this_ = static_cast<const FileChunkReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileChunkReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileChunkReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:FileChunkReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string objFilename = 1;
          if (!this_._internal_objfilename().empty()) {
            const std::string& _s = this_._internal_objfilename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileChunkReply.objFilename");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bytes chunk1024 = 2;
          if (!this_._internal_chunk1024().empty()) {
            const std::string& _s = this_._internal_chunk1024();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // int32 chunkOrder = 3;
          if (this_._internal_chunkorder() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_chunkorder(), target);
          }

          // int32 chunkTotal = 4;
          if (this_._internal_chunktotal() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_chunktotal(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:FileChunkReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileChunkReply::ByteSizeLong(const MessageLite& base) {
          const FileChunkReply& this_ = static_cast<const FileChunkReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileChunkReply::ByteSizeLong() const {
          const FileChunkReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:FileChunkReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string objFilename = 1;
            if (!this_._internal_objfilename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_objfilename());
            }
            // bytes chunk1024 = 2;
            if (!this_._internal_chunk1024().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_chunk1024());
            }
            // int32 chunkOrder = 3;
            if (this_._internal_chunkorder() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_chunkorder());
            }
            // int32 chunkTotal = 4;
            if (this_._internal_chunktotal() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_chunktotal());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileChunkReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileChunkReply*>(&to_msg);
  auto& from = static_cast<const FileChunkReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:FileChunkReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_objfilename().empty()) {
    _this->_internal_set_objfilename(from._internal_objfilename());
  }
  if (!from._internal_chunk1024().empty()) {
    _this->_internal_set_chunk1024(from._internal_chunk1024());
  }
  if (from._internal_chunkorder() != 0) {
    _this->_impl_.chunkorder_ = from._impl_.chunkorder_;
  }
  if (from._internal_chunktotal() != 0) {
    _this->_impl_.chunktotal_ = from._impl_.chunktotal_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileChunkReply::CopyFrom(const FileChunkReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FileChunkReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileChunkReply::InternalSwap(FileChunkReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.objfilename_, &other->_impl_.objfilename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chunk1024_, &other->_impl_.chunk1024_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunktotal_)
      + sizeof(FileChunkReply::_impl_.chunktotal_)
      - PROTOBUF_FIELD_OFFSET(FileChunkReply, _impl_.chunkorder_)>(
          reinterpret_cast<char*>(&_impl_.chunkorder_),
          reinterpret_cast<char*>(&other->_impl_.chunkorder_));
}

::google::protobuf::Metadata FileChunkReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EmptyMsg::_Internal {
 public:
};

EmptyMsg::EmptyMsg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:EmptyMsg)
}
EmptyMsg::EmptyMsg(
    ::google::protobuf::Arena* arena,
    const EmptyMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EmptyMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:EmptyMsg)
}

inline void* EmptyMsg::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EmptyMsg(arena);
}
constexpr auto EmptyMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EmptyMsg),
                                            alignof(EmptyMsg));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EmptyMsg::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EmptyMsg_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EmptyMsg::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<EmptyMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EmptyMsg::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<EmptyMsg>(), &EmptyMsg::ByteSizeLong,
            &EmptyMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EmptyMsg, _impl_._cached_size_),
        false,
    },
    &EmptyMsg::kDescriptorMethods,
    &descriptor_table_SceneViewer_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EmptyMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> EmptyMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::EmptyMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata EmptyMsg::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SceneFilepathsReply::_Internal {
 public:
};

SceneFilepathsReply::SceneFilepathsReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SceneFilepathsReply)
}
inline PROTOBUF_NDEBUG_INLINE SceneFilepathsReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::SceneFilepathsReply& from_msg)
      : paths_{visibility, arena, from.paths_},
        filenames_{visibility, arena, from.filenames_},
        _cached_size_{0} {}

SceneFilepathsReply::SceneFilepathsReply(
    ::google::protobuf::Arena* arena,
    const SceneFilepathsReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SceneFilepathsReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:SceneFilepathsReply)
}
inline PROTOBUF_NDEBUG_INLINE SceneFilepathsReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : paths_{visibility, arena},
        filenames_{visibility, arena},
        _cached_size_{0} {}

inline void SceneFilepathsReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SceneFilepathsReply::~SceneFilepathsReply() {
  // @@protoc_insertion_point(destructor:SceneFilepathsReply)
  SharedDtor(*this);
}
inline void SceneFilepathsReply::SharedDtor(MessageLite& self) {
  SceneFilepathsReply& this_ = static_cast<SceneFilepathsReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SceneFilepathsReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SceneFilepathsReply(arena);
}
constexpr auto SceneFilepathsReply::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SceneFilepathsReply, _impl_.paths_) +
          decltype(SceneFilepathsReply::_impl_.paths_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SceneFilepathsReply, _impl_.filenames_) +
          decltype(SceneFilepathsReply::_impl_.filenames_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SceneFilepathsReply), alignof(SceneFilepathsReply), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SceneFilepathsReply::PlacementNew_,
                                 sizeof(SceneFilepathsReply),
                                 alignof(SceneFilepathsReply));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SceneFilepathsReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SceneFilepathsReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SceneFilepathsReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SceneFilepathsReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SceneFilepathsReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SceneFilepathsReply>(), &SceneFilepathsReply::ByteSizeLong,
            &SceneFilepathsReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SceneFilepathsReply, _impl_._cached_size_),
        false,
    },
    &SceneFilepathsReply::kDescriptorMethods,
    &descriptor_table_SceneViewer_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SceneFilepathsReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> SceneFilepathsReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SceneFilepathsReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string filenames = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SceneFilepathsReply, _impl_.filenames_)}},
    // repeated string paths = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SceneFilepathsReply, _impl_.paths_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string paths = 1;
    {PROTOBUF_FIELD_OFFSET(SceneFilepathsReply, _impl_.paths_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string filenames = 2;
    {PROTOBUF_FIELD_OFFSET(SceneFilepathsReply, _impl_.filenames_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\23\5\11\0\0\0\0\0"
    "SceneFilepathsReply"
    "paths"
    "filenames"
  }},
};

PROTOBUF_NOINLINE void SceneFilepathsReply::Clear() {
// @@protoc_insertion_point(message_clear_start:SceneFilepathsReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.paths_.Clear();
  _impl_.filenames_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SceneFilepathsReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SceneFilepathsReply& this_ = static_cast<const SceneFilepathsReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SceneFilepathsReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SceneFilepathsReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:SceneFilepathsReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string paths = 1;
          for (int i = 0, n = this_._internal_paths_size(); i < n; ++i) {
            const auto& s = this_._internal_paths().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "SceneFilepathsReply.paths");
            target = stream->WriteString(1, s, target);
          }

          // repeated string filenames = 2;
          for (int i = 0, n = this_._internal_filenames_size(); i < n; ++i) {
            const auto& s = this_._internal_filenames().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "SceneFilepathsReply.filenames");
            target = stream->WriteString(2, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:SceneFilepathsReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SceneFilepathsReply::ByteSizeLong(const MessageLite& base) {
          const SceneFilepathsReply& this_ = static_cast<const SceneFilepathsReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SceneFilepathsReply::ByteSizeLong() const {
          const SceneFilepathsReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:SceneFilepathsReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string paths = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_paths().size());
              for (int i = 0, n = this_._internal_paths().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_paths().Get(i));
              }
            }
            // repeated string filenames = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_filenames().size());
              for (int i = 0, n = this_._internal_filenames().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_filenames().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SceneFilepathsReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SceneFilepathsReply*>(&to_msg);
  auto& from = static_cast<const SceneFilepathsReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SceneFilepathsReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_paths()->MergeFrom(from._internal_paths());
  _this->_internal_mutable_filenames()->MergeFrom(from._internal_filenames());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SceneFilepathsReply::CopyFrom(const SceneFilepathsReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SceneFilepathsReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SceneFilepathsReply::InternalSwap(SceneFilepathsReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.paths_.InternalSwap(&other->_impl_.paths_);
  _impl_.filenames_.InternalSwap(&other->_impl_.filenames_);
}

::google::protobuf::Metadata SceneFilepathsReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_SceneViewer_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
