// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SceneViewer.proto

#include "SceneViewer.pb.h"
#include "SceneViewer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* SceneStreamer_method_names[] = {
  "/SceneStreamer/SendSceneRequest",
};

std::unique_ptr< SceneStreamer::Stub> SceneStreamer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SceneStreamer::Stub> stub(new SceneStreamer::Stub(channel, options));
  return stub;
}

SceneStreamer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendSceneRequest_(SceneStreamer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::FileChunkReply>* SceneStreamer::Stub::SendSceneRequestRaw(::grpc::ClientContext* context, const ::SceneRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::FileChunkReply>::Create(channel_.get(), rpcmethod_SendSceneRequest_, context, request);
}

void SceneStreamer::Stub::async::SendSceneRequest(::grpc::ClientContext* context, const ::SceneRequest* request, ::grpc::ClientReadReactor< ::FileChunkReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::FileChunkReply>::Create(stub_->channel_.get(), stub_->rpcmethod_SendSceneRequest_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::FileChunkReply>* SceneStreamer::Stub::AsyncSendSceneRequestRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileChunkReply>::Create(channel_.get(), cq, rpcmethod_SendSceneRequest_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::FileChunkReply>* SceneStreamer::Stub::PrepareAsyncSendSceneRequestRaw(::grpc::ClientContext* context, const ::SceneRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::FileChunkReply>::Create(channel_.get(), cq, rpcmethod_SendSceneRequest_, context, request, false, nullptr);
}

SceneStreamer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SceneStreamer_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SceneStreamer::Service, ::SceneRequest, ::FileChunkReply>(
          [](SceneStreamer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SceneRequest* req,
             ::grpc::ServerWriter<::FileChunkReply>* writer) {
               return service->SendSceneRequest(ctx, req, writer);
             }, this)));
}

SceneStreamer::Service::~Service() {
}

::grpc::Status SceneStreamer::Service::SendSceneRequest(::grpc::ServerContext* context, const ::SceneRequest* request, ::grpc::ServerWriter< ::FileChunkReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


